name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag docker.io/bfrancom/newsboat:$(date +%s)
        echo "hi everybody!"
        docker run docker run --rm -i -v $(pwd)/config:/home/newsboat-user/.config/newsboat docker.io/bfrancom/newsboat:$(date +%s)
